# 1. Find the Sum of All Elements in a List
## Problem Statement:
Write a function to return the sum of all elements in a list.

## Example 1:
**Input:** `[1, 2, 3, 4, 5]`  
**Output:** `15`

## Example 2:
**Input:** `[10, -2, 3]`  
**Output:** `11`

In [ ]:
def sum(list):
  var=0
  for num in list:
    var+=num
  return var

list=[1, 2, 3, 4, 5]
print(sum(list))

15

# 2. Find the Maximum Element in a List
## Problem Statement:
Write a function to find the maximum element in a list.

## Example 1:
**Input:** `[3, 5, 1, 9, 2]`  
**Output:** `9`

## Example 2:
**Input:** `[10, 22, 5, 8]`  
**Output:** `22`

In [ ]:
def max(lst):
    n = len(lst)
    max_value = lst[0]
    for i in range(1, n):
        if lst[i] > max_value:
            max_value = lst[i]
    return max_value

lst = [3, 5, 1, 9, 2]
print(max(lst))

9

22

# 3. Find the Minimum Element in a List
## Problem Statement:
Write a function to find the minimum element in a list.

## Example 1:
**Input:** `[4, 7, 1, 9]`  
**Output:** `1`

## Example 2:
**Input:** `[10, 15, 3, 8]`  
**Output:** `3`

In [ ]:
def min_value(lst):
    min_val = lst[0]
    for i in range(1, len(lst)):
        if lst[i] < min_val:
            min_val = lst[i]
    return min_val

lst = [4, 7, 1, 9]
print(min_value(lst))

1

3

# 4. Reverse a List
## Problem Statement:
Write a function to reverse a given list.

## Example 1:
**Input:** `[1, 2, 3, 4, 5]`  
**Output:** `[5, 4, 3, 2, 1]`

## Example 2:
**Input:** `["a", "b", "c", "d"]`  
**Output:** `["d", "c", "b", "a"]`

In [ ]:
def reverse(inputs):
     for i in range(len(inputs)):
      for j in range(i+1,len(inputs)):
        if inputs[i]<inputs[j]:
          inputs[i],inputs[j]=inputs[j],inputs[i]
     return inputs
inputs=[1, 2, 3, 4, 5]

print(reverse(inputs))

[5, 4, 3, 2, 1]

# 5. Check if a List is Palindromic
## Problem Statement:
Write a function to check if a list is the same forward and backward.

## Example 1:
**Input:** `[1, 2, 3, 2, 1]`  
**Output:** `True`

## Example 2:
**Input:** `[1, 2, 3, 4, 5]`  
**Output:** `False`

In [ ]:
def is_palindrome(lst):
    return lst == lst[::-1]

lst = [1, 2, 3, 2, 1]
print(is_palindrome(lst))

True

# 6. Count the Frequency of Elements in a List
## Problem Statement:
Write a function to count the occurrences of each element in a list.

## Example 1:
**Input:** `[1, 2, 2, 3, 3, 3]`  
**Output:** `{1: 1, 2: 2, 3: 3}`

## Example 2:
**Input:** `["a", "b", "a", "c", "c", "c"]`  
**Output:** `{"a": 2, "b": 1, "c": 3}`

In [ ]:
def cunt(list):
   freq={}
   for item in list:
     freq[item]=freq.get(item,0)+1
     new_freq=sorted(freq.items(),key=lambda x:x[0],reverse=False)
   return dict(new_freq)
list=["a", "b", "a", "c", "c", "c"]
print(cunt(list))

{'a': 2, 'b': 1, 'c': 3}

# 7. Find the Second Largest Number in a List
## Problem Statement:
Write a function to find the second largest number in a list.

## Example 1:
**Input:** `[10, 20, 4, 45, 99]`  
**Output:** `45`

## Example 2:
**Input:** `[3, 5, 7, 7, 8]`  
**Output:** `7`

In [ ]:
def second(list):
   new_var=list[0]
   second_var=list[0]
   for num in list:
     if num>new_var:
       second_var=new_var
       new_var=num
     elif num>second_var and num!=new_var:
       second_var=num
   return second_var


list=[10, 20, 4, 45, 99]
second(list)

45

# 8. Merge Two Sorted Lists
## Problem Statement:
Write a function to merge two sorted lists into a single sorted list.

## Example 1:
**Input:** `[1, 3, 5]`, `[2, 4, 6]`  
**Output:** `[1, 2, 3, 4, 5, 6]`

## Example 2:
**Input:** `[0, 2, 8]`, `[1, 3, 7]`  
**Output:** `[0, 1, 2, 3, 7, 8]`

In [ ]:
def merg(list1,list2):

   new_ist=list1+list2
   new_ist.sort()

   return new_ist
list1=[1, 3, 5]
list2=[2, 4, 6]


print(merg(list1,list2))

[1, 2, 3, 4, 5, 6]

# 9. Remove Duplicates from a List
## Problem Statement:
Write a function to remove duplicate elements from a list while maintaining order.

## Example 1:
**Input:** `[1, 2, 2, 3, 4, 4, 5]`  
**Output:** `[1, 2, 3, 4, 5]`

## Example 2:
**Input:** `["a", "b", "a", "c", "c", "d"]`  
**Output:** `["a", "b", "c", "d"]`

In [ ]:
def remove(list):
  unique=[]
  seen=set()
  for item in list:
    if item not in seen:
      unique.append(item)
      seen.add(item)

  return unique
list=[1, 2, 2, 3, 4, 4, 5]
print(remove(list))

[1, 2, 3, 4, 5]

# 10. Rotate a List by k Positions
## Problem Statement:
Write a function to rotate a list by `k` positions to the right.

## Example 1:
**Input:** `[1, 2, 3, 4, 5]`, `k=2`  
**Output:** `[4, 5, 1, 2, 3]`

## Example 2:
**Input:** `[10, 20, 30, 40, 50]`, `k=3`  
**Output:** `[30, 40, 50, 10, 20]`

In [ ]:
def rotate(list,k):
  return list[-k:] +list[:-k]
list=[10, 20, 30, 40, 50]
print(rotate(list,3))

[30, 40, 50, 10, 20]

# 11. Find the Intersection of Two Lists
## Problem Statement:
Write a function to find the common elements between two lists.

## Example 1:
**Input:** `[1, 2, 3, 4]`, `[3, 4, 5, 6]`  
**Output:** `[3, 4]`

## Example 2:
**Input:** `["apple", "banana", "cherry"]`, `["banana", "cherry", "date"]`  
**Output:** `["banana", "cherry"]`

In [ ]:
def elements(list1,list2):
    new=[]
    for item in list1:
      if item in list2 and item not in new:
         new.append(item)
    return new
list1=["apple", "banana", "cherry"]
list2=["banana", "cherry", "date"]
print(elements(list1,list2))

['banana', 'cherry']

# 12. Find the Union of Two Lists
## Problem Statement:
Write a function to return the union of two lists (without duplicates).

## Example 1:
**Input:** `[1, 2, 3]`, `[3, 4, 5]`  
**Output:** `[1, 2, 3, 4, 5]`

## Example 2:
**Input:** `["a", "b", "c"]`, `["b", "c", "d"]`  
**Output:** `["a", "b", "c", "d"]`

In [ ]:
def union(list1,list2):
     new=[]
     seen=set()
     for item in list1 or list2:
       if item not in seen:
          seen.add(item)
          new.append(item)
     return new
list1=[1, 2, 3]
list2=[3, 4, 5]
print(union(list1,list2))

[1, 2, 3, 4, 5]

# 13. Find the Difference Between Two Lists
## Problem Statement:
Write a function to return elements present in the first list but not in the second.

## Example 1:
**Input:** `[1, 2, 3, 4]`, `[2, 4, 6]`  
**Output:** `[1, 3]`

## Example 2:
**Input:** `["cat", "dog", "rabbit"]`, `["dog", "rabbit"]`  
**Output:** `["cat"]`

In [ ]:
def difference(list1,list2):
   new=[]
   seen=set()
   for item in list1:
     if item not in list2:
       if item not in seen:
          seen.add(item)
          new.append(item)
   return new
list1=["cat", "dog", "rabbit"]
list2=["dog", "rabbit"]
print(difference(list1,list2))

['cat']

# 14. Find the Mode of a List
## Problem Statement:
Write a function to return the most frequently occurring element in a list.

## Example 1:
**Input:** `[1, 2, 2, 3, 3, 3]`  
**Output:** `3`

## Example 2:
**Input:** `["apple", "banana", "apple", "cherry", "apple"]`  
**Output:** `"apple"`

In [ ]:
def frequently(lst):
    freq = {}
    for item in lst:
        freq[item] = freq.get(item, 0) + 1
        max_item = sorted(freq.items(), key=lambda x:x[1])[0]
        if len(max_item)<=5:
           return max_item[0]

    return None
lst=["apple", "banana", "apple", "cherry", "apple"]
print(frequently(lst))

apple

# 15. Flatten a Nested List
## Problem Statement:
Write a function to flatten a nested list into a single list.

## Example 1:
**Input:** `[[1, 2, [3]], 4]`  
**Output:** `[1, 2, 3, 4]`

## Example 2:
**Input:** `[["a", ["b", "c"]], "d"]`  
**Output:** `["a", "b", "c", "d"]`

In [ ]:
def nested(lst):
    new = []
    for item in lst:
        if type(item) == type(list):
            new.extend(nested(item))
        else:
            new.append(item)
    return new

list1 = [["a", ["b", "c"]], "d"]
print(nested(list1))

['a', 'b', 'c', 'd']

# 16. Find Pairs in a List That Sum to a Target Value
## Problem Statement:
Write a function to find all pairs in a list that sum to a given target.

## Example 1:
**Input:** `[1, 2, 3, 4, 5]`, `target=6`  
**Output:** `[(1, 5), (2, 4)]`

## Example 2:
**Input:** `[2, 4, 6, 8]`, `target=10`  
**Output:** `[(2, 8), (4, 6)]`

In [ ]:
def Sum_pairs(list1, target):
     new = []
     for i in range(len(list1)):
        for j in range(i + 1, len(list1)):
            if list1[i] + list1[j] == target:
                new.append((list1[i], list1[j]))
     return new

list1 = [1, 2, 3, 4, 5]
print(Sum_pairs(list1, 6))

[(1, 5), (2, 4)]

# 17. Find the Product of All Elements Except Self
## Problem Statement:
Write a function that returns a list where each index contains the product of all numbers except the number at that index.

## Example 1:
**Input:** `[1, 2, 3, 4]`  
**Output:** `[24, 12, 8, 6]`

## Example 2:
**Input:** `[5, 6, 7]`  
**Output:** `[42, 35, 30]`

In [ ]:
def product(nums):
    result = []
    for i in range(len(nums)):
        prod = 1
        for j in range(len(nums)):
            if i != j:
                prod *= nums[j]
        result.append(prod)
    return result
nums=[5, 6, 7]
print(product(nums))

[42, 35, 30]

# 18. Find the Longest Consecutive Sequence in a List
## Problem Statement:
Write a function to find the longest sequence of consecutive numbers in a list.

## Example 1:
**Input:** `[100, 4, 200, 1, 3, 2]`  
**Output:** `4  (sequence: [1, 2, 3, 4])`

## Example 2:
**Input:** `[10, 11, 12, 50, 51, 52]`  
**Output:** `3  (sequence: [10, 11, 12])`

# 19. Check if a List Contains a Sublist
## Problem Statement:
Write a function to check if a list contains a given sublist.

## Example 1:
**Input:** `[1, 2, 3, 4, 5]`, `[3, 4]`  
**Output:** `True`

## Example 2:
**Input:** `[10, 20, 30, 40]`, `[20, 50]`  
**Output:** `False`

In [ ]:
def sublist_check(lst1,lst2):
   for i in lst1:
       if i in lst2:
          return True
   return False
lst1=[1, 2, 3, 4, 5]
lst2=[3, 4]
print(sublist_check(lst1,lst2))

True

# 20. Find the Kth Largest Element in a List
## Problem Statement:
Write a function to find the `k`th largest element in a list.

## Example 1:
**Input:** `[3, 2, 1, 5, 6, 4]`, `k=2`  
**Output:** `5`

## Example 2:
**Input:** `[10, 20, 30, 40, 50]`, `k=3`  
**Output:** `30`

In [ ]:
def kth_largest(lst,k):
    lst.sort(reverse=True)
    return lst[k-1]
lst=[3, 2, 1, 5, 6, 4]
print(kth_largest(lst,2))

5

# 21. Find All Duplicates in a List
## Problem Statement:
Write a function to return a list of all duplicate elements.

## Example 1:
**Input:** `[1, 2, 3, 4, 2, 3, 5]`  
**Output:** `[2, 3]`

## Example 2:
**Input:** `[10, 10, 20, 30, 30]`  
**Output:** `[10, 30]`

In [ ]:
def dublicate(lst):
    new_lst = []
    seen = set()
    for x in lst:
        if x in seen:
          if x not in new_lst:
            new_lst.append(x)
        else:
            seen.add(x)
    return new_lst
lst=[10, 10, 20, 30, 30]
print(dublicate(lst))

[10, 30]

# 22. Partition a List into Even and Odd Elements
## Problem Statement:
Write a function to split a list into two separate lists, one containing even numbers and the other containing odd numbers.

## Example 1:
**Input:** `[1, 2, 3, 4, 5]`  
**Output:** `([2, 4], [1, 3, 5])`

## Example 2:
**Input:** `[10, 15, 20, 25]`  
**Output:** `([10, 20], [15, 25])`

In [ ]:
def partition(lst):
    even = []
    odd = []
    for x in lst:
        if x % 2 == 0:
            even.append(x)
        else:
            odd.append(x)
    return (even, odd)
lst=[10, 15, 20, 25]
print(partition(lst))

([10, 20], [15, 25])

# 23. Find the First Non-Repeating Element in a List
## Problem Statement:
Write a function to find the first element that does not repeat.

## Example 1:
**Input:** `[4, 5, 1, 2, 0, 4]`  
**Output:** `5`

## Example 2:
**Input:** `[10, 20, 10, 30, 20]`  
**Output:** `30`

In [ ]:
def not_repeat(lst):
    freq={}
    for x in lst:
        freq[x]=freq.get(x,0)+1
    for x in lst:
       if freq[x]==1:
          return x
    return None
lst=[10, 20, 10, 30, 20]
print(not_repeat(lst))

30

# 24. Sort a List Without Using Built-in Sort
## Problem Statement:
Write a function to sort a list in ascending order without using Python’s built-in sort.

## Example 1:
**Input:** `[3, 1, 4, 1, 5, 9]`  
**Output:** `[1, 1, 3, 4, 5, 9]`

## Example 2:
**Input:** `[10, 5, 2, 8]`  
**Output:** `[2, 5, 8, 10]`

In [ ]:
def sort(lst):
     for i in range(len(lst)):
      for j in range(i+1,len(lst)):
        if lst[i]>lst[j]:
          lst[i],lst[j]=lst[j],lst[i]
     return lst
lst=[3, 1, 4, 1, 5, 9]

print(sort(lst))

[1, 1, 3, 4, 5, 9]

# 25. Find All Triplets That Sum to Zero
## Problem Statement:
Write a function to find all triplets in a list that sum to zero.

## Example 1:
**Input:** `[-1, 0, 1, 2, -1, -4]`  
**Output:** `[[-1, -1, 2], [-1, 0, 1]]`

## Example 2:
**Input:** `[1, -2, 1, 0, 5]`  
**Output:** `[[-2, 1, 1]]`

In [5]:
def triplets(lst):
    new_lst1 = []
    n = len(lst)
    for i in range(n - 2):
        for j in range(i + 1, n - 1):
            for k in range(j + 1, n):
                if lst[i] + lst[j] + lst[k] == 0:
                    triplet = sorted([lst[i], lst[j], lst[k]])
                    if triplet not in new_lst1:
                        new_lst1.append(triplet)
    return new_lst1

lst = [-1, 0, 1, 2, -1, -4]
triplets_list = triplets(lst)

for triplet in triplets_list:
    print(triplet)

[-1, 0, 1]
[-1, -1, 2]